### ISSUE TITLE
Zobrazený text při rozbalení našeptávače Ulice

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#132]
Našeptávač ULICE nabízí záznamy ve formátu ulice, obec, část obce. Je nutné, aby obsahoval pouze ulici a obec.

**Comment by raugustyn** [comment]
Tak myslím že to funguje. Opět je to otázka názoru, ale uvidíme.

**Comment by rmakovec** [comment]
jo správně zobrazuje ulici, obec
