### ISSUE TITLE
Funkce doplň adresu při více než jednom záznamu

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#133]
select * from address_points
where nazev_obce = 'Praha' and nazev_casti_obce = 'Kobylisy' and cislo_domovni = '1800'

Jsou to tři záznamy č.or. 1, 9, 16. Je potřeba, aby se podobně jako na VDP zobrazily vpravo a bylo je možné vybrat.

**Comment by raugustyn** [comment]
To se musí přidělat, už jsem to zkoušel, ale rolovací a zvětšovací tabulku se mi nepodařilo udělat, viz http://www.vugtk.cz/euradin/ResizableTable.html. Naplánuju na to 6 hodin, kdyby to nešlo, tak holt se bude rolovat zápatí portálu dolů.

**Comment by raugustyn** [comment]
Zvolil jsem stránku o 15 záznamech tak, aby byla podobně vysoká jako blok vstupních polí adresy. Dynamicky se tlačítka Další, případně Předchozí, pokud je to potřeba. Také se zobrazí celkový počet záznamů, pokud je seznam větší než stránka.

**Comment by raugustyn** [comment]
Příklad: školní, nádražní, budovatelů, rooseveltova apod.

**Comment by raugustyn** [comment]
Po vybrání adresy se kromě vyplnění vstupních polí adresa zobrazí na stránce.

**Comment by rmakovec** [comment]
zadám Praha pak kobylisy (někdy mizí číslo popisné už po zadání Praha)...pak zadám č.p 1800 dám ověř adresu a False
