### ISSUE TITLE
Nenajde se hodnota adresních prvků Pod sídlištěm 18

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#134]
Mělo by se nalézt:
Pod sídlištěm 1800/9
Kobylisy
18200 Praha 8

**Comment by raugustyn** [comment]
Ono je to správně, ale dokud nebude implementována funkcionalita #144, tak to může být trochu matoucí.

Je tam totiž Pod sídlištěm 1800/9, 187/10 a 188/8. Je to vidět z datalistů i na VDP.

**Comment by raugustyn** [comment]
Po úpravě viz #133 se najdou tři záznamy 187, 188, 1800 a je možno si z nich vybrat.

**Comment by rmakovec** [comment]
Zadám Praha a ulici Pod sídlištěm, když zadávám 18 do č.p. tak zobrazuje 5 záznamů, protože to hledá i v PSČ, potvrdím č.p. tabulátorem a už jsou jen ty 3 záznamy, z nic vyberu adresu...OK.....ale pak dám ještě ověřit adresu a False
