### ISSUE TITLE
Nádražní, Lhotka neumožní číslo popisné

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#136]
Když zadáme část obce Lhotka a v ní ulici Nádražní, tak zmizí vstupní pole pro číslo popisné, orientační, evidenční a písmeno čisla orientačního.

**Comment by raugustyn** [comment]
Dotaz [1] opravdu vrátí prázdný seznam ";;;".

[1] http://www.vugtk.cz/euradin/services/rest.py/autocomplete/datalists?LocalityPart=Lhotka&Street=n%C3%A1dra%C5%BEn%C3%AD

**Comment by raugustyn** [comment]
Hm...SQL dotaz nevrátí žádné výsledky.

select cislo_domovni, cislo_orientacni, znak_cisla_orientacniho, typ_so from address_points
where nazev_casti_obce ilike '%Lhotka%' and nazev_ulice ilike '%nádražní%'
order by cislo_domovni, cislo_orientacni, znak_cisla_orientacniho, typ_so

**Comment by raugustyn** [comment]
No, ona totiž ani v části obce ani obci Lhotka žádná nádražní ulice není.

**Comment by rmakovec** [comment]
Ta hláška by tam nemusela být hned při otevření záložky

**Comment by rmakovec** [comment]
to číslo popisné mizí často

**Comment by raugustyn** [comment]
oky, udělal jsem.
