### ISSUE TITLE
Omezení hodnot v poli městský obvod

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#137]
Když je viditelné pole městský obvod, je potřeba omezit seznam v něm podle ostatních nastavených parametrů - Část obce, Ulice, PSČ

**Comment by raugustyn** [comment]
Ty tři hodnoty pole jsou spojená Obec Praha, Část obce a Číslo městského obvodu.

Jestliže je Obec=Praha, tak:
1. Vložení části obce omezí možnosti v poli Číslo městského obvodu, jestliže je jen jedno, tak ho vymaže
2. Výběr Čísla městského obvodu nastaví datalist pro Část obce na patřičné hodnoty.

**Comment by raugustyn** [comment]
!!! Při zvolení městského obvodu výběrem z datalistu se neprovede OnChange, zatím je potřeba odejít z pole pomocí tabelátoru.

**Comment by vacektom** [comment]
Vyzkoušel jsem několik variant a vypadá to v pořádku. Nezaručuju ovšem, že se nenarazí na nějakou výjimku, ale snad ne.

**Comment by vacektom** [comment]
ověřováno na adrese:

Snopkova 485/11
Kamýk
14200 Praha 4

**Comment by vacektom** [comment]
Vypadá to funkční, vyzkoušel jsem několik příkladů a sestavuje to v pohodě. To je ale jen u geokódování. Ale když vyzkouším formátování adresy, tak mi to nebere v potaz ten Městský obvod a sestaví mi to adresu bez toho čísla, což je špatně. Tu samou adresu poté zadám ve službě ověření adresy a tam se napíše při ověření False.

**Comment by raugustyn** [comment]
vidím

grr...ono se to snaží vybrat 4-tou položku ze seznamu Praha 1-Praha10, ale už tam je jenom seznam Praha 4, tj. mělo by to vybrat položku ne podle čísla, ale podle názvu položky.

**Comment by vacektom** [comment]
opraveno, už to zkontroluje i sestaví adresu v pořádku s bráním zřetele na Městský obvod v Praze.
