### ISSUE TITLE
Reverse geocoding - stránkovaný seznam výsledků

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#142]
Funkce reverse geocoding by měla vrátit záznamy stránkované, podobně jako nabídka možných variant adres.

**Comment by raugustyn** [comment]
Stránkovaný výpis se nakonec ukázal jako nesmysl.

Řešením je:
1. Rozšíření parametrů funkce NearByAddresses o výpis vzdálenosti
2. Rozšíření parametrů funkce NearByAddresses o maximální počet záznamů, implicitně 10000.
3. Vrácené záznamy se vždy třídí podle vzdálenosti, takže jsou pokaždé ve stejném pořadí.

**Comment by vacektom** [comment]
Myslím, že v pořádku. Jen je otázka, zda by šlo udělat nějaké počítadlo, které by udávalo, kolik se vygeneruje daným výběrem záznamů?

**Comment by raugustyn** [comment]
Spočítat všechny záznamy znamená v selectu zaměnit položky za count(*), to ale znamená spustit celý dotaz ještě jednou. Problémem je, že se jedná o celkovou změnu koncepce služby z metodiky. Šlo by udělat do interaktivního prostředí jako separátní nedokumentovaná funkce, která nebude popsaná v metodice.

**Comment by vacektom** [comment]
Ne, tak mě jde o to, zda to třeba ČÚZK chce, nebo ne. Je určitě dobré vědět, kolik adres se třeba v daném okruhu nachází, ale pokud to zabere zbytečně nějaký čas a problémy navíc, tak to být samozřejmě nemusí, jen mě o napadlo jako dobrá pomůcka dané služby.

**Comment by raugustyn** [comment]
jj, já to pochopil, ta myšlenka je dobrá. Pokud se to bude jmenovat 1 hodina včetně kontroly, udělám to až budou uzavřeny všechny ostatní věci.
