### ISSUE TITLE
Před sestavením adresy by mělo dojít k jejímu doplnění

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#143]
Příklad Praha, Kolovraty

http://www.vugtk.cz/euradin/services/rest.py/CompileAddress/text?&Locality=Praha&LocalityPart=Kolovraty&ExtraInformation=standard

vrátí 

Kolovraty
 Praha

**Comment by vacektom** [comment]
Tady moc nechápu jak by to mělo fungovat. Pokud zadám obec Praha a část obce Kolovraty, nedoplní se nic a sestaví se adresa tak, jak se píše výše, jen s těmito dvěma prvky, což nelze. Podle mě by měl být postup takový, že pokud nezadá uživatel všechny prvky adresy a dá možnost sestavit adresu, tak by měla vyběhnout hláška, že nejsou zadány všechny prvky adresy a je nutné doplnit ten zbývající počet jejich prvků (pokud nezadá ulici, č.p., PSČ a tyto prvky se nedoplní automaticky, tak by měl být uživatel upozorněn, aby tyto prvky doplnil - např. hláška "Nebyly zadány všechny prvky nutné k sestavení adresy, je nutné doplnit tyto prvky - ulice, č.p./č.ev., PSČ).

**Comment by vacektom** [comment]
Tady si myslím, že už to také funguje korektně. Pokud zadám obec Praha, část obce Kolovraty, automaticky se mi nabídne MOP Praha 10, z tohoto výběru mi ještě sestavení správně nejde, pak když zadám např. č.p., nebo č.ev., tak mi interaktivní výběr nalezne možnosti, e kterých lze adresu vybrat, to samé u našeptávače, když zadám nějaké počáteční písmeno, tak mi správně doplní možné adresy v dané části obce. Z tohoto interaktivního seznamu lze pak vybrat konkrétní adresu, která se správně sestaví. Pokud je tedy funkcionalita myšlena takto, tak je vše ok.
