### ISSUE TITLE
Ulice Fialková 205, Čakovičky - nenalezena

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#146]
Ulice Fialková, obec Čakovičky ač evidentně existuje (ověřeno na VDP a i v replice databáze RÚIAN), tak pomocí funkcí Geokódování, Fulltextové vyhledávání, Sestavení adresy, nenajde žádný záznam. Evidentně i v našeptávači se nabízí, doplňuje se do sloupců, ale po spuštění jakékoliv z výše uvedených funkcí se objeví jen hláška, že nebyly nalezeny žádné informace odpovídající zadání.
Přes službu VDP jsem si zjistil ID, zadal do služby Ověření identifikátoru adresy a ta mi potvrdila, že se daná adresa v DB nachází.

Hledaná adresa:
ID 26687062 
Fialková 205
25063 Čakovičky

**Comment by vacektom** [comment]
Geokódování a fulltext stále hledanou adresu nenaleznou. Pomocí služby Sestavení adresy jsou tři možnosti sestavení adresy:
  
 - Pomocí fulltextu (Adresa) - nenalezne a nesestaví adresu
  
 - Pomocí prvků adresy - sestaví adresu, ale tam jde zadat jakoukoliv adresu, takže předpokládám, že to nejde přes server a databázi, jelikož k tomu není přiděleno ani ID. Navíc když vyberu ulici z našeptávače a nedoplním název celé ulice, sestaví se ulice s tím neúplným názvem ulice.
  
 - Pomocí identifikátoru adresy se adresa sestaví správně, i když v předešlých příkladech nelze adresu nalézt. Když mám zapnutou funkci na doplnění ID, tak mi to ID nedoplní.

**Comment by raugustyn** [comment]
Vidím, v databázi ten záznam je.

**Comment by raugustyn** [comment]
Vygenerovaný požadavek na server vypadá taky oky:
http://localhost/euradin/services/rest.py/Geocode/text?&Locality=%C4%8Cakovi%C4%8Dky&LocalityPart=%C4%8Cakovi%C4%8Dky&Street=Fialkov%C3%A1&HouseNumber=205&ZIPCode=25063&ExtraInformation=standard

**Comment by raugustyn** [comment]
Je to jedna ze 109000 adres, které nemají souřadnice.

**Comment by raugustyn** [comment]
Je to jedna ze 109000 adres, které nemají souřadnice. Zkontroloval jsem zdrojový soubor VFR a opravdu 26687062 souřadnice nemá. Je to tedy vlastnost databáze RÚIAN, že nemusí ke každému adresnímu místu znát souřadnice.
