### ISSUE TITLE
Napřidává se ID u služby Sestavení adresy zadáváním pomocí jednotlivých prvků adresy

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#147]
Pokud ve službě Sestavení adresy, pomocí zadání jednotlivých prvků adresy, najdu danou adresu a vyberu, že chci přidat ID, tak se mi dané ID nedoplní.

Ověřeno na adrese:
Fillova 980/5
Krč
14000 Praha 4

**Comment by vacektom** [comment]
stále nepřidává ID.

**Comment by raugustyn** [comment]
Vidím, odkaz vypadá správně: http://localhost/euradin/services/rest.py/CompileAddress/text?&Locality=Praha&LocalityPart=Kr%C4%8D&DistrictNumber=4&Street=Fillova&HouseNumber=980&OrientationNumber=5&ZIPCode=14000&ExtraInformation=id

**Comment by vacektom** [comment]
Pokud zadám obec Praha, vyberu část obce Krč, v nabídce se mi zobrazí správně na výběr číslo městského obvodu v Praze - Praha 4, pak když zadám ulici, tak mi našeptávač na možnost zadání "fill" ulici Fillova nenabídne. Když jí ručně dopíšu, zadám číslo popisné 980, číslo orientační 5, PSČ 14000, tak se mi sice sestaví adresa (ta by se mi ale sestavila kdykoliv, i kdybych zadal nesmysl), ale objeví se mi hláška "Adresa v této kombinaci prvků nebyla nalezena", tudíž se mi při nabídce "přidej ID" tento identifikátor nepřidá, i když je adresa korektní a existuje.

**Comment by vacektom** [comment]
V pořádku, už při zadávání adresy pomocí jednotlivých prvků adresy přiřazuje ID, to mé u možnosti zadání adresních prvků pomocí fulltextu. U zadání pomocí identifikátoru se při zadání možnosti přidat ID nepřidá, což je ale asi logické, když ho pomocí toho zadávám, ale v tom případě by u této možnosti zadání adresy tato nabídka buď neměla být, nebo by měla ID také doplňovat. U funkce Geokódování je tato možnost funkční a ID se přidá.

**Comment by vacektom** [comment]
Opraveno. Základní přidávání ID u služby Sestavení adresy pomocí jednotlivých prvků adresy je již funkční.
