### ISSUE TITLE
Sestavení adresy - vyhledávání pomocí funkce fulltext

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#148]
Pokud vyhledám pomocí funkce fulltext danou adresu a vyjede mi např. 5 záznamů, pak si jeden konkrétní vyberu, zvolím, že chci sestavit adresu, tak se mi sestaví všech 5 adres a ne jen ta jedna konkrétně vybraná adresa.

Zkoušený příklad:
Fillova, Praha - 5 záznamů

**Comment by vacektom** [comment]
upravena funkcionalita. Nalezne všech pět záznamů a vypíše je, nelze najít pomocí fulltextu jen jednu konkrétní, pokud jí přesně nezadám, to lze učinit pomocí zadání přesné adresy podle jednotlivých prvků adresy. 

Je zde ovšem stále problém s tím, že některé adresy, i když jsou ověřeny, že se nachází v databázi, tak nelze pomocí fulltextu vyhledat.

**Comment by vacektom** [comment]
Stále nenajde a nesestaví např. adresu Fialková, Čakovičky. Tato adresa nemá souřadnice adresního místa, ale to by nemělo mít vliv na sestavení dané adresy ve standardizovaném tvaru, když mi fulltext tuto adresu nabízí, ale vrátí mi pak po spuštění funkce hlášku, že nebyly nalezeny žádné informace odpovídající zadání.

**Comment by raugustyn** [comment]
To bude tím, že autocomplete a full text search pracují na jiném principu.

**Comment by raugustyn** [comment]
To je dobré. Funkce parseraddress.AddressParser().fullTextSearchAddress("Fialková, Čakovičky") bez problémů najde sedm záznamů.

**Comment by raugustyn** [comment]
Pokud to pošlu skrz webovou službu, tak dostane dotaz na u'FialkovÃ¡, ÄakoviÄky'. To opět vypadá na nějaký problém s kódováním jazyka.

**Comment by raugustyn** [comment]
Já se z tý češtiny fakt picnu.

a = "Čakovičky";
a.lower() = "Čakovičky"
unicode(a).lower() = "čakovičky"

**Comment by vacektom** [comment]
Opraveno. V pořádku.
