### ISSUE TITLE
Geokódování - nemožnost výběru jednoho konkrétního záznamu pro získání souřadnic

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#151]
Pokud zadám pomocí fulltextu vyhledání adresních míst v ulici Fillova, Praha, vyjede mi správně 5 záznamů. Z nich si v interaktivní tabulce vyberu konkrétní adresu, kterou chci georeferencovat, ta se mi dovyplní do zbylých políček v zadání, ale pokud stisknu následně Najdi polohu, tak mi služba najde polohu všech pěti záznamů a ne jen toho konkrétního, vybraného. 

U vyhledání adresy pomocí jednotlivých prvků adresy se toto nestane a vyhledá se mi souřadnice pouze konkrétně vybraného pouze jednoho záznamu.

Ověřováno na:
Fillova, Praha

**Comment by vacektom** [comment]
Pokud po změně funkcionality jde o to, že se pomocí fulltextu vyhledají všechna adresní místa a nelze vybrat konkrétní z dynamické nabídky, jako tomu bylo v předešlé verzi, tak to funguje dobře. Konkrétní jednu adresu jde tedy vybrat jen pomocí identifikátoru, nebo pomocí jednotlivých prvků adresy.

Tady si tedy myslím, že to funguje korektně. Je jen otázka, zda to někde popsat v nějaké příručce, aby si nikdo nestěžoval, že nezná ovládání, nebo právě tuto pozměněnou funkcionalitu?!

**Comment by raugustyn** [comment]
jj, přesně. vpravo jsou možnosti na výběr. když stisknu vyhledat souřadnice s nevyplněnými poli, tak najde opět těch pět.

**Comment by raugustyn** [comment]
jj, přesně. vpravo jsou možnosti na výběr. když stisknu vyhledat souřadnice s nevyplněnými poli, tak najde opět těch pět.
