### ISSUE TITLE
Blízké adresy - generování rozdílných adres

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#152]
Ve službě Blízké adresy dochází ke generování stále jiných adresních míst. Stačí pouze zaměnit, že k výstupním adresám chci přiřadit ID a už mi to po vygenerování nalezne jiné adresy. Některé jsou shodné, některé jsou úplně jiné. To samé se děje, pokud pouze provedu stejný výběr po restartování služby, pomocí tlačítka Nové zadání a zadám shodné hodnoty (souřadnice y, x a délku).

**Comment by vacektom** [comment]
Chyba by podle mě mohla být v omezeném počtu výstupních adresních míst. Vypadá to, že se pokaždé generuje jen 25 záznamů, i když jich je možná v daném okruhu víc...

**Comment by raugustyn** [comment]
Ano, tohle není chyba, ale vlastnost produktu. Napraví se to realizací #142

**Comment by raugustyn** [comment]
Vyřešeno realizací #142. Oky?

**Comment by vacektom** [comment]
Myslím si, že realizací #142 je tento problém vyřešen.
