### ISSUE TITLE
Stará Chodovská 14 - nevypne MOP

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#157]
Když zadám Část obce Stará Chodovská a č.p.14, tak sice doplní adresu, ale stále zůstane vidět pole pro vstup Číslo městského obvodu v Praze. Navíc pole s AddressDiv se zobrazí a není v něm žádná adresa.

**Comment by vacektom** [comment]
Jak u geokódování, tak u ověření i sestavení adresy mi po vyhledání části obce Stará Chodovská vstup pro číslo městského obvodu v Praze uzavře. Ale adresu m to nedoplní, i když zadám č.p. 14. Navíc když vybírám část obce, tak mi to nabídku Stará Chodovská nalezne jen, když zadám do políčka výraz star, nebo Star, pokud zadám Stará, nebo stará, tak mi našeptávač nic nenabídne, i když tyto slova v názvech částí obcí jsou.

**Comment by raugustyn** [comment]
Teď teprve je to hotovo a deployováno na euradin server.

**Comment by vacektom** [comment]
V pořádku, opraveno.
