### ISSUE TITLE
Sestavení adresy - parametr "Validate"

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#159]
Při sestavení adresy je vhodné implementovat parametr Validate s implicitní hodnotou True. Pokud je True, tak se adresa před sestavením ověří a doplní z RÚIAN.

Parametr False se použije tam, kde mám adresní prvky před odesláním zkontrolovány. Tím vypne kontrolu prvků pro sestavení, čímž se služby urychlí (není prováděn dotaz do RÚIAN).

**Comment by vacektom** [comment]
Sestavení adresy pomocí zadání jednotlivých prvků adresy funguje v prohlížeči Google Chrome korektně, stejně tak sestavení adresy podle RÚIAN ID. Chybné vyhledání je jen u sestavení adresy dle fulltextu viz #166. V prohlížeči Internet Explorer je problém s našeptávačem a funkcí služby při zadávání jednotlivých prvků adresy.

**Comment by raugustyn** [comment]
Asi opět, poslední poznámku můžeme přemístit do #168 a tenhle issue uzavřít???

**Comment by vacektom** [comment]
Ano, sestavení adresy funguje v Chromu korektně, problém je jen s prohlížečem IE (viz #168). Opraveno.
