### ISSUE TITLE
Geokódování - záměna pořadí souřadnic

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#164]
U služby Geokódování je u možnosti zadávání adresy pomocí fulltextu a pomocí identifikátoru zaměněno pořadí výsledných souřadnic. První se uvádí souřadnice x, druhá souřadnice y, u geokódování pomocí prvků adresy je výsledek správně, tedy v pořadí výpisu souřadnic y, x, jak by měl správně být.

**Comment by raugustyn** [comment]
No, jak je to proboha možné???

**Comment by vacektom** [comment]
U zadávání adresy pomocí fulltextu i pomocí jednotlivých prvků adresy je pořadí souřadnic již v pořádku, u zadání pomocí identifikátoru RÚIAN jsou souřadnice pořád v opačném pořadí.

**Comment by raugustyn** [comment]
Oky, prohodil jsem i souřadnice X<->Y při zadání bodu pomocí RÚIAN Id.

**Comment by vacektom** [comment]
Teď je pořadí souřadnic správně u zadání pomocí jednotlivých prvků adresy i u RÚIAN ID, ale pokud použiju vyhledání podle fulltextu, tak tam je to zase opačně. První souřadnice y musí být vždy menší, než x. Navíc u doplňování jednotlivých prvků adresy se ztrácí řádek s číslem popisným a při změně výběru, kdy chci třeba přidat ID, tak se mi objeví hláška "Adresa v této kombinaci prvků nebyla nalezena".

**Comment by raugustyn** [comment]
To nechápu, jak se to zkazilo. Opravil jsem.

**Comment by vacektom** [comment]
V Google Chrome funguje korektně. V Internet Exploreru co se týká pořadí souřadnic taky, ale celá služba neběží tak jak má. Nefunguje našeptávač ulic, pokud zadám nejdříve obec, pak část obce, tak následně mi už nenajde našeptávač žádnou ulici, a pokud jí zadám pomocí malých písmen, tak mi to nenajde souřadnice.

**Comment by raugustyn** [comment]
Tomáši mám pocit že poslední poznámku je vhodné přemístit na #168 a tenhle issue uzavřít jako hotový. Je to tak???

**Comment by vacektom** [comment]
Ano, je to tak. Poslední komentář jsem aktualizoval na #168. Jinak problém se záměnou souřadnic je vyřešen. Jediný problém, který trvá, tak je v problému s prohlížečem IE. Opraveno.
