### ISSUE TITLE
Sestavení adresy - vypuštění nabídky Další informace jako u služby Ověřování identifikátoru adresy

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#165]
U služby Sestavení adresy se nepřídává ID, pokud zvolím tuto nabídku z položky Další informace přidat ID. Myslím, že není potřeba, když vlastně sestavujeme adresu podle daného identifikátoru. Ideální řešení je podle mě vypuštění nabídky Další informace jako u služby Ověření identifikátoru adresy, tudíž, že tato další nabídka úplně chybí. Nebo další možností je tuto další nabídku zachovat a jen zprovoznit doplnění ID do vygenerované a zformátované adresy.

**Comment by raugustyn** [comment]
Máme to tak v metodice, tak tam to id raději systémově necháme a jen zprovozním aby fungovalo.

**Comment by raugustyn** [comment]
Oky, zneviditelnil jsem na záložce "Sestavení adresy", když je zvoleno "RÚIAN Id" pole "Další informace".

**Comment by vacektom** [comment]
V pořádku.
