### ISSUE TITLE
Fulltextové vyhledávání a Sestavení adresy pomocí fulltextu - nenalezne některé adresy

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#166]
Fulltext nenalezne adresu Fialková, Čakovičky, i když evidentně v databázi je. Nevím, na jakém principu tato funkce funguje, zda tam hraje roli to, že adresní místo nemá souřadnice, ale mělo by to každopádně tyto adresy najít, stejné jako u služby "Sestavení adresy".

**Comment by vacektom** [comment]
U služby Sestavení adresy mi adresní místo bez souřadnic služba nalezne, pokud zadám adresu pomocí ID, nebo pomocí jednotlivých prvků adresy. Pokud použiji vyhledání pomocí fulltextu, tak se mi stejná adresa nenalezne. Zkoušeno na adrese zadané pomocí řetězce:
Fialková, Čakovičky

**Comment by vacektom** [comment]
Testováno i na adresním místě, kde jsou souřadnice, konkrétně na:

ID RÚIAN: 22241591
Častavina 777/5
Ruzyně
16100 Praha 6

souřadnice definičního bodu: Y = 750490,00    X = 1041506,00

Nefunkční je služba Geokódování (fulltext), Sestavení adresy (fulltext) a Fulltextové vyhledávání. Služby Ověření pomocí identifikátoru RÚIAN, Ověření adresy a ostatní možnosti zadání adresy jednotlivých vyjmenovaných služeb fungují korektně.

**Comment by raugustyn** [comment]
Vypadá to, že úprava #148 řeší i tento problém.

**Comment by vacektom** [comment]
Opraveno. V pořádku.
