### ISSUE TITLE
U položek formát a další informace pouze přepočítat URL služby

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#167]
Když najdu položky adresy, které chci hledat a poté měním formát výsledku nebo další informace, tak by se nemělo znovu vyvolávat hledání adresy. Jediné co by se mělo přepočítat by měl být řádek s adresou volání služby. ten je normálně skrytý, ale objeví se v programátorském rozhraní.

**Comment by vacektom** [comment]
V prohlížeči Google Chrome funguje korektně. V Internet Exploreru nefunguje tak, jak by mělo. Nefunguje doplnění adresy, výběr více adres při zadání ulice bez upřesňujících parametrů.

**Comment by vacektom** [comment]
Opraveno. V pořádku.
