### ISSUE TITLE
Problém s voláním služeb v IE

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#168]
Běží to úplně stejně, v našem kódu problém není, ale ten IE má zase nějaké speciální kódování UTF-8. Verze prohlížečů jsou na portálu vyjmenovány takové, aby podporovaly most advanced funkcionalitu, tj. datalisty.

Zavolejte http://localhost/euradin/services/rest.py/autocomplete/fill?RUIANType=fill&HouseNumber=1372&Street=Mezilesní
- Chrom ok
- Firefox ok
- IE chyba

Z IE přijde zcela jinak kódovaný HTTP požadavek. Opět, to je hodně low-level systémový problém, kterej bude souviset s windowsama. Ty primárně neběží v UTF-8, znaková sada textu se neustále dokolečka někam překládá. Dokonce jsem zaregistroval teorii že je to záměrné, aby jediný program, který bude dobře fungovat na windows bude ten přeložený překladačem Microsoft Visual Studio.

Zkusím to, dám tomu hodinu.

**Comment by raugustyn** [comment]
Tak to je dobrý. Zarazí se to už na prvním řádku mojeho kódu, uvnitř knihovní funkce web.input(). Jako že core knihovny Pythonu. Tohle vypadá, že asi nezlomím.

**Comment by vacektom** [comment]
Tak pak je asi jako jediná možnost prohlásit, že v prohlížeči IE nejsou služby RÚIAN možné podporovat z těchto relevantních důvodů. A nechat jen podporované prohlížeče Chrome, Firefox a nevím jak je to s Operou.

**Comment by raugustyn** [comment]
Jednoduše v té knihovně v modulu web/utils.py na rádku 348 zhavaruje obj.decode(encoding). obj="Mezilesní" a encoding="utf-8".

Když to pošlu z Chrome nebo Firefoxu, tak je dokonce vidět Mezilesní správně a všechno proběhne. Když to pošlu z IE, tak poslední písmeno je paznak.

**Comment by raugustyn** [comment]
Tak Chrome a Firefox zakódujou "Mezilesní" jako 'Mezilesn\xc3\xad', Internet Explorer jako 'Mezilesn\xed'.

Handling URL request
======================================================
Parsing query
Parsing itemMiniFieldStorage('RUIANType', 'fill')
Value=fill
Parsing itemMiniFieldStorage('Street', 'Mezilesn\xed')
======================================================
Handling URL request
Parsing query
Parsing itemMiniFieldStorage('RUIANType', 'fill')
Value=fill
Parsing itemMiniFieldStorage('Street', 'Mezilesn\xc3\xad')
Value=Mezilesní
End of Parsing query

**Comment by vacektom** [comment]
V Google Chrome funguje služba Geokódování korektně. V Internet Exploreru co se týká pořadí souřadnic taky, ale celá služba neběží tak jak má. Nefunguje našeptávač ulic, pokud zadám nejdříve obec, pak část obce, tak následně mi už nenajde našeptávač žádnou ulici, a pokud jí zadám pomocí malých písmen, tak mi to nenajde souřadnice.

**Comment by vacektom** [comment]
Sestavení adresy pomocí zadání jednotlivých prvků adresy funguje v prohlížeči Google Chrome korektně, stejně tak sestavení adresy podle RÚIAN ID. Chybné vyhledání je jen u sestavení adresy dle fulltextu viz #166. V prohlížeči Internet Explorer je problém s našeptávačem a funkcí služby při zadávání jednotlivých prvků adresy.

**Comment by raugustyn** [comment]
Tak jsem to asi spravil, ještě nemám úplně otestováno ale vypadá to oky. Nemám rád IE!!!

Viz https://github.com/vugtk21/RUIANToolbox/commit/4143eea1b3a6d4de896d1dc018dd6fe720a8a714

**Comment by vacektom** [comment]
U služeb Geokódování (zadávání jednotlivých prvků adres),  Sestavení adresy (zadávání jednotlivých prvků adres) a Ověření adresy služba funguje v pořádku, když zadám název části ulice, tam se objeví našeptávač, po vybrání se objeví interaktivní okno s nabídkou dostupných adres, jedna se vybere a vše je ok. Pokud ovšem zadám nejdříve obec (tam se objeví našeptávač v pořádku), pak část obce (zde už se objeví našeptávač, ve kterém mohu vybírat pouze myší, šipkami se tam nedostanu, to samé u MOP), pak když přejdu k zadání ulice, tak se už našeptávač neobjeví, ale když zadám třeba jen první písmeno názvu ulice a zmáčknu tlačítko "doplň adresu", tak se objeví interaktivní okno se správnými adresami, ve které vyberu a je to ok. U Chromu se ovšem objeví hned našeptávač ulic, kde vyberu název ulice a nemusím stisknout tlačítko "doplň adresu".
Jinak ale kromě těchto odlišností fungují služby i v IE, jen s trochu jiným postupem.

**Comment by raugustyn** [comment]
Vybírání z datalistů pomocí klávesnice vytaženo do #169

**Comment by vacektom** [comment]
V pořádku. Opraveno.
