### ISSUE TITLE
Fulltext - vyhledávání č.p., č.ev., č.or. a PSČ

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#173]
Pokud zadáme např. ulici Cílkova 1, tak se vyhledává ve všech částech adresy, kde je číslo (č.p., č.ev., č.or. a PSČ). Nevyhledává se ale pouze číslice 1, ale i ostatní, kde je jednička obsažena. Problém je to zejména u vyhledávání v PSČ, kde číslici jedna obsahuje drtivá většina adres. Bylo by dobré vyhledávat jen dle konkrétní zadané číslice v parametrech č.p., č.ev., č.or. a v PSČ vyhledávat, jen když uživatel zadá pětimístné číslo, jinak v PSČ nevyhledávat.

**Comment by raugustyn** [comment]
Jo, myslím že to tak už je:
Budovatelů 35735
Cílkova 1
apod.

**Comment by vacektom** [comment]
Upraveno. V pořádku.
