### ISSUE TITLE
Práce s menším územím - aktualizace

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#174]
Pokud si v importéru zadám jako zájmové území pro práci jen obec, nebo menší část území, tak by bylo dobré zajistit, aby se při stahování aktualizačních balíčků netahaly informace z celého území, ale jen informace z dané lokality, nad kterou pracuji. Tzn. nestahovat aktualizace z obcí, které nejsou v DB.

**Comment by raugustyn** [comment]
Množství kombinací a parametrů pro stahování z VDP je logicky veliké a těžko vysledovat všechny varianty. Tohle je jenom jedna z nich. Parsovat url adresu z VDP a podle ní něco dělat by asi bylo nad rámec skutečných potřeb.

**Comment by raugustyn** [comment]
Ve verzi 1.9.74 byl vytvořen SQl script, který se spouští po importu do databáze, do kterého lze přidat případné vymazání účelové nadbytečných záznamů, generování dalších pomocných tabulek apod. Také byla upravena dokumentace.

**Comment by vacektom** [comment]
Kde je upravená dokumentace, ze které je to zřejmé? To je upraveno v ověřené technologii, nebo v certifikované metodice?

**Comment by raugustyn** [comment]
Strana 16:
Uživatelská úprava databáze po importu
Jestliže potřebujeme po importu databáze upravit nějaké tabulky, vygenerovat své vlastní účelové tabulky, případně vymazat záznamy nějakého typu, je možné vložit příslušné SQL příkazy do souboru RUIANServices\SQLScripts\AfterImport.sql.
-- ##################################################
-- Tento SQL skript se spustí po importu dat do databáze
-- Můžeme využít k vytvoření vlastních pomocných tabulek nebo k vymazání některých záznamů.
-- ##################################################

**Comment by raugustyn** [comment]
Jako nejjednodušší způsob otestování bych viděl přídání create table do toho skriptu a spuštění aktualizace dat na serveru euradin, bu'd v adresáři FullDB nebo AddressDB.

**Comment by raugustyn** [comment]
Postačí přidat tabulku k vytvoření: CREATE TABLE temptable(gid integer) WITH (OIDS=FALSE);
