### ISSUE TITLE
Znovu zkontrolovat pravopis na portálu, například "cerifikovanou" na hlavní stránce.

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#176]

**Comment by vacektom** [comment]
Pravopis až na jednu čárku, kdy je uvedeno RUIAN místo správného RÚIAN,  v dolní části vedle loga TA ČR. Správné znění "Webové služby RÚIAN byly vytvořeny v rámci projektu TB01CUZK004: Výzkum uplatnění závěrů projektu eContentplus s názvem EURADIN v podmínkách RÚIAN (2012-2014)".

**Comment by vacektom** [comment]
Opraveno. V pořádku.
