### ISSUE TITLE
Ve fulltextu pro čísla nedávat like%, ale like

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#177]
Ing. Doubek: Když se ve fulltextu použije číslo, tak ho uživatel většinou zná, tzn. je dobré nepovažovat ho za počátek čísla k doplnění. Jak to je teď když třeba vím číslo orientační 20, tak mi to nabídne všechna čísla popisná a orientační která obsahují 20. Když je ulice dlouhá, tak tu svojí 20 budu mít někde schovanou.

**Comment by raugustyn** [comment]
No, to zní logicky. Díval jsem se na mapy.seznam.cz a podle mají mazaně vymyšlený řešení. Jako obvykle je to odhad nejčastějšího USE CASE.

Budovatelů 6....vrátí 10 záznamů, kde je přesně číslo 6
Budovatelů 67...nikde republice není přesně 67, vrátí tedy všechny 4 záznamy, která aspoň začínají mna těch 67

**Comment by raugustyn** [comment]
Take jsem to tak udělal.

1. Pro každý z výsledků se vypočítá míra shody záznamu RÚIAN a full text požadavku.
2. Možnosti se setřídí podle míry shody
3. Jestliže první záznam má 100% shodu:
* tak se vrátí jenom záznamy kde ta shoda je 100%
* jinak se všechny pravděpodobné záznamy

**Comment by raugustyn** [comment]
K pochopení jak to funguje stačí vyzkoušet tyto příklady:
Budovatelů 6
Budovatelů 67
Budovatel 6

**Comment by vacektom** [comment]
Upraveno. V pořádku.
