### ISSUE TITLE
Úprava certifikované metodiky

### ISSUE THREAD

**Issue by vacektom** [vugtk21/RUIANToolbox#178]
Nevím zda se to může, ale pokud deklarujeme pouze využití webových služeb ve standardu REST, měla by se v certifikované metodice smazat kapitola, kde deklarujeme použití služeb i ve standardu SOAP/WSDL, včetně přílohy k tomu vytvořené.

**Comment by raugustyn** [comment]
Jedna věc je metodika, druhá její implementace a třetí ověřená technologie.

1. V metodice to je
2. Implementováno to je
3. Na resortu neměli sílu si to zkontrolovat, takže jsem to z portálu vyhodil.

Já myslím, že to je konzistentní. Deklarujeme navenek to, co si ČÚZK ověřil že je oky.

**Comment by vacektom** [comment]
Ok, pokud to myslíte takhle a je to obhajitelné, tak s tím nemám problém. V tom případě je to v pořádku, jen mi to přišlo divné, že to někde je a ve výsledku ne, ale v pohodě.

**Comment by raugustyn** [comment]
jo, funkčnost toho kdykoli předvedu, je to jenom jinak zavolaný rest, ale střeva uvnitř jsou oky.
