### ISSUE TITLE
Nedostupná závislost: OSGeo4W_vfr.zip

### ISSUE THREAD

**Issue by wodCZ** [vugtk21/RUIANToolbox#183]
Zdravím,

nevím zda se jedná o dočasný výpadek, nebo o nějaké omezení přístupu z internetu, ale nedaří se mi stáhnout knihovnu/aplikaci z adresy http://geo1.fsv.cvut.cz/landa/vfr/OSGeo4W_vfr.zip

**Comment by raugustyn** [comment]
Dobré odpoledne,

také vidím že to nejde.

Český úřad nás v určité fázi přinutil vytvořit zálohu na našem serveru, vidím že měli pravdu najdete to [zde](http://www.vugtk.cz/euradin/VFRLibrary/Default.htm), v dokumentaci je to uvedeno na straně 6 v kapitole Instalace :-) :-).

Martinovi dám vědět že mu ten server nějak neběží, ten odkaz je na aktuální verzi ČVÚT, certifikaci jsme prováděli na té stabilizované.

Díky za info

**Comment by wodCZ** [comment]
Dobré odpoledne,

odkaz na mě vyskočil v terminálu, v `RUIANToolbox.pdf` jsem si odkazu nevšiml (máte samozřejmě pravdu, je tam)

Každopádně vám mnohokrát děkuji.

PS: issue vám nechám otevřenou, kdyby nějaký kolemjdoucí byl stejně nepozorný jako já a zasekl se na instrukci z terminálu – případně si ji prosím zavřete vy. 

Děkuji.

**Comment by raugustyn** [comment]
jj, martin píše že má havárii na serveru. tak ještě že nás ten ČÚZK přinutil udělat replikaci.

mějte se

Radek Augustýn

![bez nazvu](https://cloud.githubusercontent.com/assets/3672235/11146347/e86f1d5c-8a0d-11e5-96a9-38eb2e0f96a7.png)
